language: ruby
rvm:
  - 2.4.1
notifications:
	email: false
  slack:
    secure: OTnKzUYprEmDrTC0W9t0YBvBexMKatjwM3Utp1uI9DZT54yxmAaJ7zioY/omGUJNddpmFISas4rLDFn02opf+b6xRxTTZ8B6tJg6cI1xPmHWogUXiL7GgzhTLmjMnXkM5fouu7WQA+y50S32js+q2fcdANLFuJ+1VOb14qPNrHijhO6BT41p8F7X644NzHFEv8OYepeX+fNHdYN4L9ZoDEWAVR4UPitVtqzLXJBM4B/USUiZzmCP4Sr85h+enk2xz/SkV3WSeho2VlgLWkueIOjKFPvq0686hQaevuc3chiUQGnWgh4x+LXm98pHbNWjNr0MRISIqdM1HOT+06XboYDFbZtkpI1uKx7q1uePBSJ19btND8y4IzZlgqPlJ4Y71nho1a2tJDtkYDQ9UXIMPgP07g3rc71Eh4nGxkX1b0LB4Hpx++h0mWfv/ksMo3N5t7sSR2tuY8o84DZo8jU0MRk4Lm7GIt1rhwwrEUMX6V0ZEwiV2a+vLuWWpUz9VKOjjfYbyefI5ag+4tuHgusJajUQYU6iDy4euIYmDvNnCG0AWmp3b7gDyI6YZDGmOdqVhqXXDykakA3BHVpb/Mj5veeq8P/UCA4QcqHLhANbn9QGmlK5ZVKXogRbChbcwH0ZcqQTURX58KPBYNyrOTKW1Jw6tir+JYLuNPbLbns1h/c=
