language: ruby
rvm:
- 2.4.1
notifications:
  email: false
  slack:
    secure: sayDcWha4gypxlJMbWPd4euC+DasxB7hNar7y4jX8eGgXwMfzgf/EwGIIsfPCqo01iHlA44h9O9IgZ5RFq+ToHOKAEXIb8gxhBmtM9wMfxmDDQyLsMc1a5gUXQnMkLKJDOH/BF+eeJ7YFWDtMlrr4DUzxHJlMtIy/OYh7Hr0CS14QGbt7CmPUTX09OrtiUAuuPchgRslzTs8vXYO+360V/Oghr0LK9GZMIXO/7T6pFRokyq7fRskHy3BQtolqMNrP/vd4NFa/hnViLtSHVdo8rhbU4GbgoQ5HwSzthVmkCXP3n1dCVnPrw8/XQ4moL8mqJQC+tIxdaZklAa0lMA9Swz59iAi3sdlcyLJV9LnZBX4wFq2IVaUsXg2gIZgru1a0UTx23gqmUbikALXA2KjjR+41OSzGUSEzi+TENYk3vCJ6Ucz2iUR0twcj5eOSVUY7l2giCMZXSzRdTNF1zL6L5P/NGCS3nRe1QpTQYiOHqhvwX7K9mUFsqIIZcyaszGT/n5bERskk2KiptHZB8YmTwWZuP52ujJKnk0vxcwOubD3Q5UiCP0m/OiKeRcyG6YpSygpRUfZ54Dbk7Bvr3L4Dq2MooBaiY0qnlVrocgFX2f5RQGGRt+uNhHeUbKClpNA0pGK+c85H5fnSk+H7jGOn+n8yJO+v0qrfpt+tnDouXE=
