language: ruby
rvm:
- 2.4.1
notifications:
  email: false
  slack:
    secure: f80MtoGKneJKMwlbje7NZujBJQ7K+S67sxQFYFZGLeVxBf9GErtfx0aPJFUrfXLVAV23r7+3CTJFL45zqiVO0g5QBpwuFUqJ2VdJBlAIcIKVfbPmCWOmcXVbG7jnFqY7sZ7NUlpRzfnhXv0rMWypOdQKjblgBGHDf8faB4Wwo0xbxi5jlxzzO52imsqzqftcSgIy7qQJ2ou8tUM5Su/fv6LDYKIkJxxcYPbRiWDdLSWWR3Bia/I8f9+7KhHPgGhaYLGngWena7G8yPD99XQjZ4wisBPmGmB47PnIrdJXAn0F7ZahQdTs17i5xQ33r/K6LeAn6zoEF/7NpauylhHi09SDtoahbfgKVFk6UHwBToZuikJlJAwMwdTenL16W7YoyjfcGyvOwYH4bJohbEU9/CDgonGcuiiJ3YLryns8ZvsOZog3bl8B8phclZOnCv9jQ75qhY2QxJOh4qT1PomuAL1xbCy7/BJV6X73WeN8ftnpGzMb+DmAWDJ/+3fnlWiOlgEHq9qF60lVPENudHDTtB7CSYy+2XfY+tNe5ryh4Hw66vOMesfzAWBwFbLpOtX629u+O9KBkXuA1obibEj0NqUhSUBZtp1MnOwrzYKcHXJmIMnuae2thN8m8Q04hqNqfcB+ela2crCZ9gvTs5Bfx17EFCz7s2Q5hSexaZwZH5w=
